version: "3"
services:
  splash:
    image: scrapinghub/splash

  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: scrapy

  scrapyminerov:
    ports:
      - "8080:8080"
    build:
      context: ./scrapyminerov
    depends_on:
      - db
